apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
  namespace: mysql
  labels:
    app: mysql
spec:
  replicas: 3
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: mysql
          image: 788814499739.dkr.ecr.us-east-1.amazonaws.com/flask-mysql-ecr:mysql-latest
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "rootpassword"
            - name: MYSQL_DATABASE
              value: "employees"
            - name: MYSQL_USER
              value: "db_user"
            - name: MYSQL_PASSWORD
              value: "db_password"

